import styles from '@/styles/Login.module.css';
import Head from 'next/head';

const LoginPage = () => {
  return (
    <>
      <Head>
        <title>Ob - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <input placeholder="Username"></input>
          <input placeholder="Password"></input>

          <div className={styles.wrapper}>
            <span className={styles.register}>Register</span>

            <span className={styles.buttonWrapper}>
              <span>login</span>
              <button></button>
            </span>
          </div>
        </div>
      </main>
    </>
  );
};

export default LoginPage;
