import styles from '@/styles/CV.module.css';
import Head from 'next/head';
import Image from 'next/image';

const Index = () => {
  return (
    <>
      <Head>
        <title>Ob - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={`${styles.main__section} ${styles.projects}`}>
          Projects
        </section>

        <section className={styles.main__sectionImage}>
          <Image alt="piano" src="/images/piano.jpeg" fill />
        </section>

        <section className={styles.main__sectionImage}>
          <Image alt="piano" src="/images/keyboard.jpeg" fill />
        </section>

        <section className={`${styles.main__section} ${styles.resume}`}>
          Resume
        </section>
      </main>
    </>
  );
};

export default Index;
