import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Ondi Butarbutar — Software Engieer</title>
        <title>Ob — Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.main__description}>
          <main className={styles.main__Title}>Software Enginner.</main>
          <p>
            I&#39;m Ondi Frans Butarbutar, a Software Engineer — currently
            working at Bank Negara Indonesia, and have delivered
            mission-focused, data-driven projects and new features that drive
            results and help achieve business goals I&#39;m{' '}
          </p>
        </div>

        <button className={styles.main__circleButton}>X</button>

        <Link href="/Resume">
          <button className={styles.main__circleButton}>X</button>
        </Link>
      </main>
    </>
  );
}
