import styles from '@/styles/Home.module.css';
import { Inter } from '@next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ondi Butarbutar — Software Engieer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <div className={styles.main__description}>
          <main className={styles.main__Title}>Software Enginner.</main>
          <p>
            I&#39;m Ondi Frans Butarbutar, a Software Engineer — currently
            working at Bank Negara Indonesia, and have delivered
            mission-focused, data-driven projects and new features that drive
            results and help achieve business goals
          </p>
        </div>

        <button className={styles.main__circleButton}>X</button>
      </div>
    </>
  );
}
